### ISSUE TITLE
"abap.builtin.insert is not a function" error in Atbash Cipher

### ISSUE THREAD

**Issue by suynwa** [exercism/abap#124]
When running the tests for the following code for Atbash Cipher:

```abap
CLASS zcl_atbash_cipher DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS decode
      IMPORTING
        cipher_text       TYPE string
      RETURNING
        VALUE(plain_text) TYPE string.
    METHODS constructor.
    METHODS encode
      IMPORTING
        plain_text         TYPE string
      RETURNING
        VALUE(cipher_text) TYPE string.

  PRIVATE SECTION.
    DATA plain_latin   TYPE string.
    DATA atbash_cipher TYPE string.

    METHODS conv_to_target_character_set
      IMPORTING
        text               TYPE string
        from_character_set TYPE string
        to_character_set   TYPE string
      RETURNING
        VALUE(result)      TYPE string.

    METHODS get_cipher_text
      IMPORTING
        ungrouped_cipher_text TYPE string
      RETURNING
        VALUE(cipher_text)    TYPE string.
ENDCLASS.


CLASS zcl_atbash_cipher IMPLEMENTATION.
  METHOD constructor.
    plain_latin = to_lower( sy-abcde ).
    atbash_cipher = to_lower( reverse( sy-abcde ) ).
  ENDMETHOD.

  METHOD decode.
    DATA(input) = to_lower( cipher_text ).
    CONDENSE input NO-GAPS.

    plain_text = conv_to_target_character_set(
                     text               = input
                     from_character_set = atbash_cipher
                     to_character_set   = plain_latin ).
  ENDMETHOD.

  METHOD conv_to_target_character_set.
    DO strlen( text ) TIMES.
      DATA(alphabet) = substring(
                           val = text
                           off = sy-index - 1
                           len = 1 ).

      result = result &&
                    COND #(
                      WHEN alphabet CO '0123456789' THEN alphabet
                      ELSE substring( val = to_character_set
                                      off = find( val = from_character_set sub = alphabet )
                                      len = 1 ) ).
    ENDDO.
    CONDENSE result.
  ENDMETHOD.

  METHOD encode.
    DATA(input) = replace(
                      val   = to_lower( plain_text )
                      regex = `[^a-z0-9]` ##REGEX_POSIX
                      with  = space
                      occ   = 0 ).

    CONDENSE input NO-GAPS.

    cipher_text = get_cipher_text( conv_to_target_character_set(
                                       text               = input
                                       from_character_set = plain_latin
                                       to_character_set   = atbash_cipher ) ).

  ENDMETHOD.

  METHOD get_cipher_text.
    cipher_text = ungrouped_cipher_text.
    DATA(offset) = 6.
    DATA(cipher_text_length) = strlen( cipher_text ).
    WHILE offset <= cipher_text_length - 1.
      cipher_text = insert( val = cipher_text sub = ` ` off = offset - 1 ).
      cipher_text_length = strlen( cipher_text ).
      offset += 6.
    ENDWHILE.
  ENDMETHOD.

ENDCLASS.
```

i am getting the following error:

> TypeError: abap.builtin.insert is not a function
>     at zcl_atbash_cipher.get_cipher_text (file:///tmp/exercism-abap-runner-uGgrIG/compiled/zcl_atbash_cipher.clas.mjs:70:36)
>     at zcl_atbash_cipher.encode (file:///tmp/exercism-abap-runner-uGgrIG/compiled/zcl_atbash_cipher.clas.mjs:57:32)
>     at async ltcl_test.encode5 (file:///tmp/exercism-abap-runner-uGgrIG/compiled/zcl_atbash_cipher.clas.testclasses.mjs:27:67)
>     at async Function.run (file:///tmp/exercism-abap-runner-uGgrIG/compiled/kernel_unit_runner.clas.mjs:126:11)
>     at async run (file:///tmp/exercism-abap-runner-uGgrIG/compiled/index_open.mjs:59:17)

I assume that the [insert](https://help.sap.com/doc/abapdocu_756_index_htm/7.56/en-US/index.htm?file=abeninsert_functions.htm) string function is not yet implemented

**Comment by larshp** [comment]
yup, not implemented yet, https://github.com/abaplint/transpiler/tree/main/packages/runtime/src/builtin

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/702

**Comment by larshp** [comment]
@suynwa try again, 

![image](https://user-images.githubusercontent.com/5888506/162607030-19448019-36f7-428b-b9d8-4e5395ff6992.png)
