### ISSUE TITLE
case of `INTO` matters

### ISSUE THREAD

**Issue by christianguenter2** [exercism/abap#179]
ITAB AGGREGATION

```
LOOP AT initial_numbers REFERENCE into DATA(line).

ENDLOOP.
```
gives error
TypeError: line.assign is not a function
    at zcl_itab_aggregation.perform_aggregation (file:///tmp/exercism-abap-runner-SK8YjS/compiled/zcl_itab_aggregation.clas.mjs:18:12)
    at ltcl_itab_aggregation.one_row (file:///tmp/exercism-abap-runner-SK8YjS/compiled/zcl_itab_aggregation.clas.testclasses.mjs:59:89)
    at Function.run (file:///tmp/exercism-abap-runner-SK8YjS/compiled/kernel_unit_runner.clas.mjs:128:77)
    at async run (file:///tmp/exercism-abap-runner-SK8YjS/compiled/_unit_open.mjs:53:17)

while this runs (note the uppercase INTO)
```
LOOP AT initial_numbers REFERENCE INTO DATA(line).

ENDLOOP.
```

This error only occurs when REFERENCE is used.

**Comment by larshp** [comment]
@christianguenter2 try again, downport updated

**Comment by christianguenter2** [comment]
works :+1 
closing
