### ISSUE TITLE
ITAB Nesting: 'Error Variable name "temp3" already defined (check_syntax)' at Assigning Reference to Table Expression

### ISSUE THREAD

**Issue by bau-mann** [exercism/abap#209]
Error Message: 

```
./zcl_itab_nesting.clas.abap[66, 9] - Variable name "temp3" already defined (check_syntax) [E]
./zcl_itab_nesting.clas.abap[87, 9] - Incompatible types (check_syntax) [E]
abaplint: 2 issue(s) found
```

Source Code:
```abap
  METHOD perform_nesting.
    LOOP AT artists REFERENCE INTO DATA(artist).
      APPEND CORRESPONDING #( artist->* ) TO nested_data.
      DATA(nested_artist) = REF #( nested_data[ artist_id = artist->artist_id ] ).
      LOOP AT albums REFERENCE INTO DATA(album) WHERE artist_id = artist->artist_id.
        APPEND CORRESPONDING #( album->* ) TO nested_artist->albums.
        DATA(nested_album) = REF #( nested_artist->albums[ album_id = album->album_id ] ). " <<< The error occurs here
        "LOOP AT songs REFERENCE INTO DATA(song) WHERE artist_id = artist->artist_id AND album_id = album->album_id.
          "APPEND CORRESPONDING #( song->* ) TO nested_album->songs.
        "ENDLOOP.
      ENDLOOP.
    ENDLOOP.
  ENDMETHOD.
```

The same source code does run in the current ABAP Environment on SAP BTP.

**Comment by bau-mann** [comment]
Here is a variation of the source code above:
```
  METHOD perform_nesting.
    LOOP AT artists REFERENCE INTO DATA(artist).
      APPEND CORRESPONDING #( artist->* ) TO nested_data REFERENCE INTO DATA(nested_artist).
      LOOP AT albums REFERENCE INTO DATA(album) WHERE artist_id = artist->artist_id.
        APPEND CORRESPONDING #( album->* ) TO nested_artist->albums REFERENCE INTO DATA(nested_album).  " <<< The error occurs here
        "LOOP AT songs REFERENCE INTO DATA(song) WHERE artist_id = artist->artist_id AND album_id = album->album_id.
          "APPEND CORRESPONDING #( song->* ) TO nested_album->songs.
        "ENDLOOP.
      ENDLOOP.
    ENDLOOP.
  ENDMETHOD.
```

That returns this error message:
```
TypeError: Cannot read properties of undefined (reading 'albums')
    at zcl_itab_nesting.perform_nesting (file:///tmp/exercism-abap-runner-QfXet4/compiled/zcl_itab_nesting.clas.mjs:32:75)
    at async ltcl_itab_nesting.test_single_artist (file:///tmp/exercism-abap-runner-QfXet4/compiled/zcl_itab_nesting.clas.testclasses.mjs:69:68)
    at async Function.run (file:///tmp/exercism-abap-runner-QfXet4/compiled/kernel_unit_runner.clas.mjs:133:11)
    at async run (file:///tmp/exercism-abap-runner-QfXet4/compiled/_unit_open.mjs:33:17)
```

**Comment by larshp** [comment]
@bau-mann try again

![image](https://user-images.githubusercontent.com/5888506/192856382-34aa0fea-c89e-42f9-b5ca-cbb11349c8d7.png)

![image](https://user-images.githubusercontent.com/5888506/192856262-d27522cd-0ee1-4299-bccd-414aaf09ff35.png)

**Comment by bau-mann** [comment]
@larshp It works! Thank you very much.
