### ISSUE TITLE
Error "Not a structure, FieldChain (check_syntax)" for Atbash Cipher

### ISSUE THREAD

**Issue by BaerbelW** [exercism/abap#257]
Hi All!

After cobbling together a working solution for the Atbash Cipher exercise in a NW 7.50 system, I copied it over to Exercism and got several errors, most of which I could identify and correct. I'm however mystiefied by the last two as I (yet again) cannot really match it to specific code lines:

./zcl_atbash_cipher.clas.abap[71, 9]  - Not a structure, FieldChain (check_syntax) [E]
./zcl_atbash_cipher.clas.abap[134, 9] - Not a structure, FieldChain (check_syntax) [E]

Here is my code (not yet "neat" by any stretch of the imagination, but wanted to get a working solution before tackling improvements):

```abap
CLASS zcl_atbash_cipher DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    METHODS decode
      IMPORTING
        cipher_text       TYPE string
      RETURNING
        VALUE(plain_text) TYPE string .
    METHODS encode
      IMPORTING
        plain_text         TYPE string
      RETURNING
        VALUE(cipher_text) TYPE string .
  PROTECTED SECTION.
  PRIVATE SECTION.
    TYPES:
      ty_collected_strings TYPE STANDARD TABLE OF string WITH DEFAULT KEY.
    DATA: a_to_z(26) TYPE c, 
          z_to_a(26) TYPE c,
          decoding_letter(1) TYPE c VALUE 'abcdefghijklmnopqrstuvwxyz',
          encoding_letter(1) TYPE c VALUE 'zyxwvutsrqponmlkjihgfedcba'.
    METHODS cut_string_and_reassemble
      CHANGING
        c_cipher_text TYPE string.
ENDCLASS.

CLASS zcl_atbash_cipher IMPLEMENTATION.

  METHOD decode.

    DATA: BEGIN OF line_cipher,
            cipher(1) TYPE c,
            plain(1)  TYPE c,
          END OF   line_cipher.

    DATA: decoding_table LIKE STANDARD TABLE OF line_cipher.

    DO 26 TIMES.
      DATA(index) = sy-index - 1.
      decoding_table = VALUE #( BASE decoding_table ( cipher = z_to_a+index(1)
                                                       plain = a_to_z+index(1) ) ).

    ENDDO.

    DATA(length_cipher) = strlen( cipher_text ).

    DO length_cipher TIMES.
      index = sy-index - 1.
      IF cipher_text+index(1) EQ space.
        CONTINUE.
      ENDIF.

      READ TABLE decoding_table WITH KEY cipher = cipher_text+index(1)
                                    INTO decoding_letter.

      IF sy-subrc EQ 0.
        CONCATENATE plain_text
                    decoding_letter-plain
               INTO plain_text.
      ELSE.
        CONCATENATE plain_text
                    cipher_text+index(1)
               INTO plain_text.
        CONDENSE plain_text NO-GAPS.
      ENDIF.

    ENDDO.

  ENDMETHOD.

  METHOD encode.

    DATA: BEGIN OF line_encode,
            plain(1)  TYPE c,
            cipher(1) TYPE c,
          END OF   line_encode.

    DATA: encoding_table LIKE STANDARD TABLE OF line_encode.
    DATA: cnt_to_five TYPE i.
    DATA: lv_special_chars(50) TYPE c VALUE '. _ ! " & / = + : , - ( ) # @ % ^ $ | ~ '.
    DATA: collected_strings TYPE STANDARD TABLE OF string WITH DEFAULT KEY.

    DO 26 TIMES.
      DATA(index) = sy-index - 1.
      encoding_table = VALUE #( BASE encoding_table ( plain = a_to_z+index(1)
                                                     cipher = z_to_a+index(1) ) ).
    ENDDO.

    DATA(plain_text_lc) = plain_text.
    TRANSLATE plain_text_lc TO LOWER CASE.
    TRANSLATE plain_text_lc USING lv_special_chars.
    CONDENSE plain_text_lc.

    DATA(length_plain) = strlen( plain_text_lc ).

    CLEAR cnt_to_five.

    DO length_plain TIMES.
      index = sy-index - 1.

      READ TABLE encoding_table WITH KEY plain = plain_text_lc+index(1)
                                    INTO encoding_letter.

      IF sy-subrc EQ 0.
        CONCATENATE cipher_text
                    encoding_letter-cipher
               INTO cipher_text.
      ELSE.
        CONCATENATE cipher_text
                    plain_text_lc+index(1)
               INTO cipher_text.
      ENDIF.

    ENDDO.

    CONDENSE cipher_text NO-GAPS.
    DATA(length_cipher) = strlen( cipher_text ).

    IF length_cipher GT 5.
      cut_string_and_reassemble(
                                CHANGING
                                  c_cipher_text = cipher_text ).
    ENDIF.

  ENDMETHOD.

  METHOD cut_string_and_reassemble.

    DATA collected_strings TYPE ty_collected_strings.

    "Longer strings need to be cut into blocks of 5 characters
    DATA(single_unit_len) = 5.
    "Get length of string that will be processed
    DATA(remaining_strlen) = strlen( c_cipher_text ).
    "While string is not processed fully, loop across this algorithm.
    WHILE remaining_strlen NE 0.
      "The length to be processed at once can have 2 different values.
      "The full single_unit_len length or a smaller remaining part.
      DATA(unit_len) = COND #(
                              WHEN remaining_strlen > single_unit_len 
                              THEN single_unit_len
                              ELSE remaining_strlen
                              ).
      "Copy a single unit out of the string.
      DATA(single_unit) = substring( val = c_cipher_text
                                     len = unit_len
                                    ).
      "Cut the copied out unit out of the string
      c_cipher_text = substring( val = c_cipher_text off = unit_len len = remaining_strlen - unit_len  ).
      "Get the new remaining length.
      remaining_strlen = strlen( c_cipher_text ).
      "Append the single unit to a string table.
      collected_strings = VALUE #( BASE collected_strings ( single_unit ) ).
    ENDWHILE.

    CLEAR c_cipher_text.
    LOOP AT collected_strings INTO DATA(block_of_chars).
      IF sy-tabix EQ 1.
        c_cipher_text = block_of_chars.
      ELSE.
        c_cipher_text = c_cipher_text && ` ` && block_of_chars.
      ENDIF.
    ENDLOOP.

  ENDMETHOD.

ENDCLASS.
```

Thanks much and cheers
Bärbel

**Comment by larshp** [comment]
looks there is a syntax error, 

![image](https://user-images.githubusercontent.com/5888506/209931997-c089db03-b71d-498a-ae25-e5e1e596334a.png)

**Comment by BaerbelW** [comment]
Ooops, sorry that happened while trying to sort out the other errors and too quickly changing the code. I corrected the code and it is working and passing all tests in an actual system. 

```
      READ TABLE decoding_table WITH KEY cipher = cipher_text+index(1)
                                     **INTO line_cipher.**

      IF sy-subrc EQ 0.
        CONCATENATE plain_text
                    **line_cipher-plain**
               INTO plain_text.
      ELSE.
        CONCATENATE plain_text
                    cipher_text+index(1)
               INTO plain_text.
        CONDENSE plain_text NO-GAPS.
      ENDIF.
```
and

```
      READ TABLE encoding_table WITH KEY plain = plain_text_lc+index(1)
                                    **INTO line_encode.**

      IF sy-subrc EQ 0.
        CONCATENATE cipher_text
                    **line_encode-cipher**
               INTO cipher_text.
      ELSE.
        CONCATENATE cipher_text
                    plain_text_lc+index(1)
               INTO cipher_text.
      ENDIF.
```

On Exercism I now get this rather cryptic error though:

SyntaxError: Invalid regular expression: /+/: Nothing to repeat
    at new RegExp (<anonymous>)
    at Statements.translate (/usr/local/lib/node_modules/@abaplint/runtime/build/src/statements/translate.js:20:43)
    at zcl_atbash_cipher.encode (file:///tmp/exercism-abap-runner-alf53V/compiled/zcl_atbash_cipher.clas.mjs:89:21)
    at ltcl_test.encode1 (file:///tmp/exercism-abap-runner-alf53V/compiled/zcl_atbash_cipher.clas.testclasses.mjs:17:92)
    at kernel_unit_runner.run (file:///tmp/exercism-abap-runner-alf53V/compiled/kernel_unit_runner.clas.mjs:135:77)
    at async run (file:///tmp/exercism-abap-runner-alf53V/compiled/_unit_open.mjs:73:17)

Given that I don't do anything with REGEX in the code, I'm wondering if this could have to do with either this data defintion containing a "+":
DATA: lv_special_chars(50) TYPE c VALUE '. _ ! " & / = + : , - ( ) # @ % ^ $ | ~ '.

Or any of the substring assignments used in the code?

Or is the error a bit of a red herring and it's something else completely?

Cheers
Bärbel

**Comment by larshp** [comment]
thats a bug in the transpiler runtime, reproduced as

```abap
DATA lv_special_chars(50) TYPE c VALUE '. _ ! " & / = + : , - ( ) # @ % ^ $ | ~ '.
DATA plain_text_lc TYPE string.
plain_text_lc = 'foo'.
TRANSLATE plain_text_lc USING lv_special_chars.
ASSERT plain_text_lc = 'foo'.
```

![image](https://user-images.githubusercontent.com/5888506/209938590-af300066-d1f4-473a-a72c-4460aae859e1.png)

**Comment by larshp** [comment]
https://github.com/abaplint/transpiler/pull/1041

**Comment by larshp** [comment]
@BaerbelW try again, exercism runner updated

https://github.com/exercism/abap-test-runner/pull/173

**Comment by BaerbelW** [comment]
@larshp - Thanks, Lars, it's working now and executing all tests successfully!

Cheers and Happy New Year!
Bärbel
