### ISSUE TITLE
ITAB-Aggregation error when using FOR .. IN GROUP with DATA REFERENCE

### ISSUE THREAD

**Issue by brehberg** [exercism/abap#280]
I ran into the following error when attempting to solve ITAB Aggregation exercise.  It works on ABAP AS, but not on exercism.
<img width="501" alt="image" src="https://github.com/exercism/abap/assets/596239/df58e6db-139f-4318-b5e7-e91ad10c3917">

I was using LOOP .. GROUP BY .. REFERENCE INTO DATA(key) and then had a nested FOR expression with FOR .. IN GROUP key

It did work after changing the group_result to simply use INTO DATA(key) instead of the data reference. 
Here is a link to my published solutions on Exercism: https://exercism.org/tracks/abap/exercises/itab-aggregation/solutions/brehberg

**Comment by brehberg** [comment]
CLASS zcl_itab_aggregation DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    TYPES group TYPE c LENGTH 1.
    TYPES: BEGIN OF initial_numbers_type,
             group  TYPE group,
             number TYPE i,
           END OF initial_numbers_type,
           initial_numbers TYPE STANDARD TABLE OF initial_numbers_type WITH EMPTY KEY.

    TYPES: BEGIN OF aggregated_data_type,
             group   TYPE group,
             count   TYPE i,
             sum     TYPE i,
             min     TYPE i,
             max     TYPE i,
             average TYPE f,
           END OF aggregated_data_type,
           aggregated_data TYPE STANDARD TABLE OF aggregated_data_type WITH EMPTY KEY.

    METHODS perform_aggregation
      IMPORTING
        initial_numbers        TYPE initial_numbers
      RETURNING
        VALUE(aggregated_data) TYPE aggregated_data.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS zcl_itab_aggregation IMPLEMENTATION.

  METHOD perform_aggregation.

    LOOP AT initial_numbers REFERENCE INTO DATA(record)
      GROUP BY ( group = record->group
                 size = GROUP SIZE
                ) REFERENCE INTO DATA(key).

      DATA(aggregate) = REDUCE aggregated_data_type(
        INIT result = VALUE #(
            group = key->group
            count = key->size
            min = cl_abap_math=>max_int4
            max = cl_abap_math=>min_int4 )
        FOR member IN GROUP key
        NEXT result = VALUE #( BASE result
          sum = result-sum + member-number
          min = nmin( val1 = result-min val2 = member-number )
          max = nmax( val1 = result-max val2 = member-number )
        ) ).

      APPEND VALUE #( BASE aggregate
        average = aggregate-sum / aggregate-count
      ) TO aggregated_data.
    ENDLOOP.

  ENDMETHOD.

ENDCLASS.

**Comment by MoHa173** [comment]
I got an error by using reduce and also on using conditions!

```ABAP
CLASS zcl_itab_aggregation DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    TYPES group TYPE c LENGTH 1.
    TYPES: BEGIN OF initial_numbers_type,
             group  TYPE group,
             number TYPE i,
           END OF initial_numbers_type,
           initial_numbers TYPE STANDARD TABLE OF initial_numbers_type WITH EMPTY KEY.

    TYPES: BEGIN OF aggregated_data_type,
             group   TYPE group,
             count   TYPE i,
             sum     TYPE i,
             min     TYPE i,
             max     TYPE i,
             average TYPE f,
           END OF aggregated_data_type,
           aggregated_data TYPE STANDARD TABLE OF aggregated_data_type WITH EMPTY KEY.

    METHODS perform_aggregation
      IMPORTING
        initial_numbers        TYPE initial_numbers
      RETURNING
        VALUE(aggregated_data) TYPE aggregated_data.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.



CLASS zcl_itab_aggregation IMPLEMENTATION.
  METHOD perform_aggregation.
    " add solution here
       data(temp) = initial_numbers.
    sort temp by group ascending.
    delete adjacent duplicates from temp comparing group.

    loop at temp into data(temp_line).

      data new_group type aggregated_data_type.
      new_group-group = temp_line-group.

      loop at initial_numbers into data(group) where group = temp_line-group.
        new_group-count = new_group-count + 1.
        new_group-sum   = new_group-sum + group-number.
        new_group-min   = cond #( when new_group-min = 0            then group-number
                                  when group-number < new_group-min then group-number
                                  else                                   new_group-min ).
        new_group-max   = cond #( when group-number > new_group-max
                                  then group-number
                                  else new_group-max ).
      endloop.
      new_group-average = new_group-sum / new_group-count.
      
      append new_group to aggregated_data.
      clear new_group.
    endloop.
  ENDMETHOD.

ENDCLASS.
```

We received the following error when we ran your code:

Transpiler CLI
Using config: abap_transpile.json
117 files added from source
0 files skipped in source

Building
Error: CondBodyTranspiler, Expected Cond, todo, Source
    at CondBodyTranspiler.transpile (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:80167:23)
    at SourceTranspiler.transpile (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:82089:61)
    at Traversal.traverseExpression (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:93572:31)
    at Traversal.traverse (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:92756:25)
    at MoveTranspiler.transpile (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:88925:32)
    at Traversal.traverseStatement (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:93561:38)
    at Traversal.traverse (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:92753:25)
    at LoopTranspiler.transpile (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:92161:55)
    at Traversal.traverseStructure (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:93540:40)
    at Traversal.traverse (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:92750:25)

```ABAP
class zcl_itab_aggregation definition
  public final
  create public.

  public section.
    types group type c length 1.
    types: begin of initial_numbers_type,
             group  type group,
             number type i,
           end of initial_numbers_type,
           initial_numbers type standard table of initial_numbers_type with empty key.

    types: begin of aggregated_data_type,
             group   type group,
             count   type i,
             sum     type i,
             min     type i,
             max     type i,
             average type f,
           end of aggregated_data_type,
           aggregated_data type standard table of aggregated_data_type with empty key.

    methods perform_aggregation
      importing initial_numbers        type initial_numbers
      returning value(aggregated_data) type aggregated_data.

endclass.


class zcl_itab_aggregation implementation.
  method perform_aggregation.
    " add solution here

    data(temp) = initial_numbers.
    sort temp by group ascending.
    delete adjacent duplicates from temp comparing group.

    loop at temp into data(temp_line).
      data new_group type aggregated_data_type.
      new_group-count   = lines( filter #( initial_numbers using key group where group = temp_line-group ) ).
      
      new_group-sum     = reduce i( init sum = 0 for number in initial_numbers where ( group = temp_line-group ) next sum = sum + number-number ).
      
      new_group-min     = reduce i( init min = 999999 for number in initial_numbers where ( group = temp_line-group )
                                 next min = cond #( when number-number < min then number-number else min ) ).
      new_group-max     = reduce i( init max = 0 for number in initial_numbers where ( group = temp_line-group )
                                 next max = cond #( when number-number > max then number-number else max ) ).
      new_group-average = new_group-sum / new_group-count.
      append new_group to aggregated_data.
    endloop.
  endmethod.
endclass.
```

Transpiler CLI
Using config: abap_transpile.json
117 files added from source
0 files skipped in source

Building
Error: CondBodyTranspiler, Expected Cond, todo, Source
    at CondBodyTranspiler.transpile (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:80167:23)
    at SourceTranspiler.transpile (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:82089:61)
    at Traversal.traverseExpression (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:93572:31)
    at Traversal.traverse (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:92756:25)
    at ReduceBodyTranspiler.transpile (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:81818:44)
    at SourceTranspiler.transpile (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:82122:74)
    at Traversal.traverseExpression (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:93572:31)
    at Traversal.traverse (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:92756:25)
    at MoveTranspiler.transpile (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:88925:32)
    at Traversal.traverseStatement (/usr/local/lib/node_modules/@abaplint/transpiler-cli/build/bundle.js:93561:38)

**Comment by larshp** [comment]
@MoHa173 thanks, can you help updating the comment with code blocks, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

**Comment by MoHa173** [comment]
Hey @larshp it seams that the JS Script has problems with conditioins I tried a version with reduce and also a version with second loop and COND from both I got JavaScript errors. I updated my comment

**Comment by larshp** [comment]
thanks, if you have time, https://transpiler.abaplint.org can be used to reduce the example

then after that, next step is to implement a fix in https://github.com/abaplint/transpiler, and get that released

I'm out of town this week, so feel free to ping me in this thread when I forget to look into it 😅
